### ISSUE TITLE
TypeError: can't convert nil into String 

### ISSUE THREAD

**Issue by matthewepler** [datamapper/dm-core#183]
I have already deployed this app to herouku and it was working fine. I went in to make some aesthetic changes, and started to get this error. I'm really new to Ruby, bash, and heroku - so I assume I did something I shouldn't have. Any guidance will be much appreciated.

In the code below, "Can" is a class created in DataMapper. I then migrated and updated to sqlite and pushed to heroku. 

<pre>

>> require 'app.rb'
=> true
>> Can.count
TypeError: can't convert nil into String
    from /Library/Ruby/Gems/1.8/gems/data_objects-0.10.7/lib/data_objects/connection.rb:79:in `initialize'
    from /Library/Ruby/Gems/1.8/gems/data_objects-0.10.7/lib/data_objects/connection.rb:79:in `send'
    from /Library/Ruby/Gems/1.8/gems/data_objects-0.10.7/lib/data_objects/connection.rb:79:in `__new'
    from /Library/Ruby/Gems/1.8/gems/data_objects-0.10.7/lib/data_objects/pooling.rb:177:in `new'
    from /Library/Ruby/Gems/1.8/gems/data_objects-0.10.7/lib/data_objects/pooling.rb:172:in `synchronize'
    from /Library/Ruby/Gems/1.8/gems/data_objects-0.10.7/lib/data_objects/pooling.rb:172:in `new'
    from /Library/Ruby/Gems/1.8/gems/data_objects-0.10.7/lib/data_objects/pooling.rb:119:in `new'
    from /Library/Ruby/Gems/1.8/gems/data_objects-0.10.7/lib/data_objects/connection.rb:68:in `new'
    from /Library/Ruby/Gems/1.8/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:251:in `open_connection'
    from /Library/Ruby/Gems/1.8/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
    from /Library/Ruby/Gems/1.8/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:141:in `read'
    from /Library/Ruby/Gems/1.8/gems/dm-core-1.2.0/lib/dm-core/repository.rb:162:in `read'
    from /Library/Ruby/Gems/1.8/gems/dm-core-1.2.0/lib/dm-core/collection.rb:1117:in `lazy_load'
    from /Library/Ruby/Gems/1.8/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:409:in `each'
    from /Library/Ruby/Gems/1.8/gems/dm-core-1.2.0/lib/dm-core/collection.rb:504:in `each'
    from /Library/Ruby/Gems/1.8/gems/dm-core-1.2.0/lib/dm-core/model.rb:317:in `each'
    from (irb):2:in `count'
    from (irb):2>> 
</pre>

**Comment by ghost** [comment]
"TypeError: can't convert nil into String" is an ineffective way to say the database is not found.  Maybe the project maintainer(s) can make it say a more helpful error.
