### ISSUE TITLE
Requirements missing?

### ISSUE THREAD

**Issue by fabianfrz** [datamapper/dm-core#285]
I had to add this two require statements into my file otherwise it crashes
```ruby
require 'stringio'
require 'psych'
```

ruby version:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

trace for missing stringio
```
/usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core.rb:114:in `<top (required)>': uninitialized constant StringIO (NameError)
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/lib/ruby/gems/2.2.0/gems/datamapper-1.2.0/lib/data_mapper.rb:12:in `block in <top (required)>'
        from /usr/lib/ruby/gems/2.2.0/gems/datamapper-1.2.0/lib/data_mapper.rb:11:in `each'
        from /usr/lib/ruby/gems/2.2.0/gems/datamapper-1.2.0/lib/data_mapper.rb:11:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from ./test.rb:26:in `<main>'
```

trace for missing psych
```
/usr/lib/ruby/gems/2.2.0/gems/dm-serializer-1.2.2/lib/dm-serializer/to_yaml.rb:15:in `included': undefined method `add_domain_type' for Psych:Module (NoMethodError)
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `include'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `block in extended'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `each'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `extended'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:71:in `extend'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:71:in `included'
```
in this line: include DataMapper::Resource

**Comment by fabianfrz** [comment]
it also happens in IRB:
```
irb(main):001:0> require 'data_mapper'
NameError: uninitialized constant StringIO
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core.rb:114:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/lib/ruby/gems/2.2.0/gems/datamapper-1.2.0/lib/data_mapper.rb:12:in `block in <top (required)>'
        from /usr/lib/ruby/gems/2.2.0/gems/datamapper-1.2.0/lib/data_mapper.rb:11:in `each'
        from /usr/lib/ruby/gems/2.2.0/gems/datamapper-1.2.0/lib/data_mapper.rb:11:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1                                                                                                                                                                 
        from /usr/bin/irb:11:in `<main>'
```

**Comment by tpitale** [comment]
Could not reproduce on ruby 2.3.0 and data mapper 1.2.0:

```
▶ gem install data_mapper
Fetching: dm-core-1.2.1.gem (100%)
Successfully installed dm-core-1.2.1
Fetching: dm-validations-1.2.0.gem (100%)
Successfully installed dm-validations-1.2.0
Fetching: uuidtools-2.1.5.gem (100%)
Successfully installed uuidtools-2.1.5
Fetching: stringex-1.5.1.gem (100%)
Successfully installed stringex-1.5.1
Fetching: bcrypt-3.1.10.gem (100%)
Building native extensions.  This could take a while...
/Users/tpitale/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /Users/tpitale/.bin in PATH, mode 040777
Successfully installed bcrypt-3.1.10
Fetching: bcrypt-ruby-3.1.5.gem (100%)

#######################################################

The bcrypt-ruby gem has changed its name to just bcrypt.  Instead of
installing `bcrypt-ruby`, you should install `bcrypt`.  Please update your
dependencies accordingly.

#######################################################

Successfully installed bcrypt-ruby-3.1.5
Fetching: dm-types-1.2.2.gem (100%)
Successfully installed dm-types-1.2.2
Fetching: dm-transactions-1.2.0.gem (100%)
Successfully installed dm-transactions-1.2.0
Fetching: dm-timestamps-1.2.0.gem (100%)
Successfully installed dm-timestamps-1.2.0
Fetching: json_pure-1.8.3.gem (100%)
Successfully installed json_pure-1.8.3
Fetching: dm-serializer-1.2.2.gem (100%)
Successfully installed dm-serializer-1.2.2
Fetching: dm-migrations-1.2.0.gem (100%)
Successfully installed dm-migrations-1.2.0
Fetching: dm-constraints-1.2.0.gem (100%)
Successfully installed dm-constraints-1.2.0
Fetching: dm-aggregates-1.2.0.gem (100%)
Successfully installed dm-aggregates-1.2.0
Fetching: data_mapper-1.2.0.gem (100%)
Successfully installed data_mapper-1.2.0
Parsing documentation for dm-core-1.2.1
Installing ri documentation for dm-core-1.2.1
Parsing documentation for dm-validations-1.2.0
Installing ri documentation for dm-validations-1.2.0
Parsing documentation for uuidtools-2.1.5
Installing ri documentation for uuidtools-2.1.5
Parsing documentation for stringex-1.5.1
Installing ri documentation for stringex-1.5.1
Parsing documentation for bcrypt-3.1.10
Installing ri documentation for bcrypt-3.1.10
Parsing documentation for bcrypt-ruby-3.1.5
Installing ri documentation for bcrypt-ruby-3.1.5
Parsing documentation for dm-types-1.2.2
Installing ri documentation for dm-types-1.2.2
Parsing documentation for dm-transactions-1.2.0
Installing ri documentation for dm-transactions-1.2.0
Parsing documentation for dm-timestamps-1.2.0
Installing ri documentation for dm-timestamps-1.2.0
Parsing documentation for json_pure-1.8.3
Installing ri documentation for json_pure-1.8.3
Parsing documentation for dm-serializer-1.2.2
Installing ri documentation for dm-serializer-1.2.2
Parsing documentation for dm-migrations-1.2.0
Installing ri documentation for dm-migrations-1.2.0
Parsing documentation for dm-constraints-1.2.0
Installing ri documentation for dm-constraints-1.2.0
Parsing documentation for dm-aggregates-1.2.0
Installing ri documentation for dm-aggregates-1.2.0
Parsing documentation for data_mapper-1.2.0
Installing ri documentation for data_mapper-1.2.0
Done installing documentation for dm-core, dm-validations, uuidtools, stringex, bcrypt, bcrypt-ruby, dm-types, dm-transactions, dm-timestamps, json_pure, dm-serializer, dm-migrations, dm-constraints, dm-aggregates, data_mapper after 7 seconds
15 gems installed
~                                                                                                                                                                                
▶ irb
irb(main):001:0> require 'data_mapper'
=> true
```
