### ISSUE TITLE
Failed to setup DB with some ASCII characters in file path

### ISSUE THREAD

**Issue by haibison** [datamapper/dm-core#289]
For example this setup will fail:

```ruby
DataMapper.setup :default, 'sqlite:///path/#/!!db.sqlite'
```

Log:

```sh
/usr/local/share/gems/gems/data_objects-0.10.16/lib/data_objects/connection.rb:79:in `initialize': unable to open database file (DataObjects::ConnectionError)
        from /usr/local/share/gems/gems/data_objects-0.10.16/lib/data_objects/connection.rb:79:in `new'
        from /usr/local/share/gems/gems/data_objects-0.10.16/lib/data_objects/pooling.rb:181:in `block in new'
        from /usr/local/share/gems/gems/data_objects-0.10.16/lib/data_objects/pooling.rb:176:in `synchronize'
        from /usr/local/share/gems/gems/data_objects-0.10.16/lib/data_objects/pooling.rb:176:in `new'
        from /usr/local/share/gems/gems/data_objects-0.10.16/lib/data_objects/pooling.rb:121:in `new'
        from /usr/local/share/gems/gems/data_objects-0.10.16/lib/data_objects/connection.rb:68:in `new'
        from /usr/local/share/gems/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:251:in `open_connection'
        from /usr/local/share/gems/gems/dm-transactions-1.2.0/lib/dm-transactions/adapters/dm-do-adapter.rb:69:in `open_connection'
        from /usr/local/share/gems/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
        from /usr/local/share/gems/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:33:in `select'
        from /usr/local/share/gems/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-sqlite-adapter.rb:43:in `table_info'
        from /usr/local/share/gems/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-sqlite-adapter.rb:18:in `storage_exists?'
        from /usr/local/share/gems/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:65:in `storage_exists?'
        from /usr/local/share/gems/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:120:in `storage_exists?'
        from /usr/local/share/gems/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/model.rb:22:in `auto_migrate_constraints_down'
        from /usr/local/share/gems/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/singleton_methods.rb:39:in `block in auto_migrate_constraints_down'
        from /usr/local/share/gems/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb:64:in `block in each'
        from /usr/local/share/gems/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb:211:in `block in each'
        from /usr/local/share/gems/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `block in each'
        from /usr/local/share/gems/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `each'
        from /usr/local/share/gems/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `each'
        from /usr/local/share/gems/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb:211:in `each'
        from /usr/local/share/gems/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb:63:in `each'
        from /usr/local/share/gems/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/singleton_methods.rb:38:in `auto_migrate_constraints_down'
        from /usr/local/share/gems/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/singleton_methods.rb:7:in `auto_migrate!'
```

Would you please fix this bug?

Thank you.

**Comment by tpitale** [comment]
Moved to data_objects
