### ISSUE TITLE
Use array of hashes to populate `has n` dependency generates exceptions

### ISSUE THREAD

**Issue by craibuc** [datamapper/dm-core#301]
# Model

`foo.rb`:

``` ruby
module Api
  class Foo
    include DataMapper::Resource

    property :id, Serial    
    property :name, String, :required => true, :unique => true

    has n, :bars
  end
end
```

`bar.rb`:

``` ruby
module Api
  class Bar
    include DataMapper::Resource

    property :id, Serial    
    property :name, String, :required => true, :unique => true

    belongs_to :foo
  end
end
```
# Cases
## Case I

Creating parent and dependencies together works as expected:

``` ruby
IRB> f=Api::Foo.create(name:'foo0')
=> #<Api::Foo @id=1 @name="foo0">
IRB>  f.save
=> true
IRB>  bb=[{name:'bar0'},{name:'bar1'},{name:'bar2'}]
=> [{:name=>"bar0"}, {:name=>"bar1"}, {:name=>"bar2"}]
IRB>  f.bars
=> []
IRB>  f.bars=bb
=> [{:name=>"b0"}, {:name=>"b1"}, {:name=>"b2"}]
IRB>  f.save
=> true
IRB>  f.bars
=> [#<Api::Bar @id=1 @name="bar0" @foo_id=1>, #<Api::Bar @id=2 @name="bar1" @foo_id=1>, #<Api::Bar @id=3 @name="bar2" @foo_id=1>]
```
## Case II

Create the parent, then exit IRB:

``` ruby
IRB> f=Api::Foo.create(name:'foo1')
=> #<Api::Foo @id=2 @name="foo1">
IRB> f.save
=> true
IRB> exit
```

 Re-start IRB, then create the dependencies:

``` ruby
IRB> f=Api::Foo.all(:name.like=>'foo1')
=> [#<Api::Foo @id=2 @name="foo1">]
IRB> f.bars
=> []
IRB> bb=[{name:'bar0'},{name:'bar1'},{name:'bar2'}]
=> [{:name=>"bar0"}, {:name=>"bar1"}, {:name=>"bar2"}]
IRB> f.bars=bb
NoMethodError: undefined method `bars=' for [#<Api::Foo @id=2 @name="foo1">]:DataMapper::Collection
    from /Users/x/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:426:in `method_missing'
    from /Users/x/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:1449:in `method_missing'
    from (irb):5
    from /Users/x/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
>> f.bars << bb
NoMethodError: undefined method `saved?' for [{:name=>"bar0"}, {:name=>"bar1"}, {:name=>"bar2"}]:Array
    from /Users/x/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:1303:in `resource_added'
    from /Users/x/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:537:in `<<'
    from (irb):6
    from /Users/x/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
```
# Environment

``` bash
$ gem list --local sql*

*** LOCAL GEMS ***

dm-sqlite-adapter (1.2.0)
do_sqlite3 (0.10.17)

$ gem list --local dm-*

*** LOCAL GEMS ***

dm-aggregates (1.2.0)
dm-constraints (1.2.0)
dm-core (1.2.1)
dm-do-adapter (1.2.0)
dm-migrations (1.2.0)
dm-serializer (1.2.2)
dm-sqlite-adapter (1.2.0)
dm-timestamps (1.2.0)
dm-transactions (1.2.0)
dm-types (1.2.2)
dm-validations (1.2.0)

$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```

**Comment by tpitale** [comment]
You call `.all` to assign `f`. You need to use `.first` or `.get`. All returns a collection. This leads to the error you're seeing.
